/* Generated by tools/gen_p386_layout.py; do not edit by hand.
 * Included after p386 VM/bytecode structs are declared.
 */
#ifndef P386_LAYOUT_H
#define P386_LAYOUT_H

#include <stddef.h>

#define P386_LAYOUT_STATIC_ASSERT(name, cond) \
    typedef char p386_layout_static_assert_##name[(cond) ? 1 : -1]

/* These offsets are for the 32-bit DOS ABI used by the NASM dispatcher. */
#ifdef __386__
P386_LAYOUT_STATIC_ASSERT(pointer_size_32bit, sizeof(void *) == 4);

P386_LAYOUT_STATIC_ASSERT(p386_value_size, sizeof(P386Value) == 8);
P386_LAYOUT_STATIC_ASSERT(p386_value_value, offsetof(P386Value, value) == 0);
P386_LAYOUT_STATIC_ASSERT(p386_value_tag, offsetof(P386Value, tag) == 4);
P386_LAYOUT_STATIC_ASSERT(loaded_program_size, sizeof(P386LoadedProgram) == 20);
P386_LAYOUT_STATIC_ASSERT(loaded_program_buf, offsetof(P386LoadedProgram, buf) == 0);
P386_LAYOUT_STATIC_ASSERT(loaded_program_buf_size, offsetof(P386LoadedProgram, buf_size) == 4);
P386_LAYOUT_STATIC_ASSERT(loaded_program_protos, offsetof(P386LoadedProgram, protos) == 8);
P386_LAYOUT_STATIC_ASSERT(loaded_program_string_entries, offsetof(P386LoadedProgram, string_entries) == 12);
P386_LAYOUT_STATIC_ASSERT(loaded_program_bytecode_section, offsetof(P386LoadedProgram, bytecode_section) == 16);
P386_LAYOUT_STATIC_ASSERT(vm_status, offsetof(P386VMState, status) == 0);
P386_LAYOUT_STATIC_ASSERT(vm_error_msg, offsetof(P386VMState, error_msg) == 4);
P386_LAYOUT_STATIC_ASSERT(vm_last_opcode, offsetof(P386VMState, last_opcode) == 8);
P386_LAYOUT_STATIC_ASSERT(vm_program, offsetof(P386VMState, program) == 12);
P386_LAYOUT_STATIC_ASSERT(vm_value_stack, offsetof(P386VMState, value_stack) == 32);
P386_LAYOUT_STATIC_ASSERT(vm_base, offsetof(P386VMState, base) == 32800);
P386_LAYOUT_STATIC_ASSERT(vm_top, offsetof(P386VMState, top) == 32804);
P386_LAYOUT_STATIC_ASSERT(vm_value_stack_end, offsetof(P386VMState, value_stack_end) == 32808);
P386_LAYOUT_STATIC_ASSERT(vm_globals, offsetof(P386VMState, globals) == 32812);
P386_LAYOUT_STATIC_ASSERT(vm_current_proto, offsetof(P386VMState, current_proto) == 41004);
P386_LAYOUT_STATIC_ASSERT(vm_ip, offsetof(P386VMState, ip) == 41008);
P386_LAYOUT_STATIC_ASSERT(call_frame_return_ip, offsetof(P386CallFrame, return_ip) == 0);
P386_LAYOUT_STATIC_ASSERT(call_frame_return_base, offsetof(P386CallFrame, return_base) == 4);
P386_LAYOUT_STATIC_ASSERT(call_frame_return_proto, offsetof(P386CallFrame, return_proto) == 8);
P386_LAYOUT_STATIC_ASSERT(call_frame_return_closure, offsetof(P386CallFrame, return_closure) == 12);
P386_LAYOUT_STATIC_ASSERT(call_frame_return_reg, offsetof(P386CallFrame, return_reg) == 16);
P386_LAYOUT_STATIC_ASSERT(call_frame_want_rets, offsetof(P386CallFrame, want_rets) == 17);
P386_LAYOUT_STATIC_ASSERT(call_frame_size, sizeof(P386CallFrame) == 32);
P386_LAYOUT_STATIC_ASSERT(call_frame_saved_vararg_base, offsetof(P386CallFrame, saved_vararg_base) == 20);
P386_LAYOUT_STATIC_ASSERT(call_frame_saved_vararg_count, offsetof(P386CallFrame, saved_vararg_count) == 24);
P386_LAYOUT_STATIC_ASSERT(call_frame_saved_vararg_sp, offsetof(P386CallFrame, saved_vararg_sp) == 28);
P386_LAYOUT_STATIC_ASSERT(vm_current_closure, offsetof(P386VMState, current_closure) == 41012);
P386_LAYOUT_STATIC_ASSERT(vm_open_upvalues, offsetof(P386VMState, open_upvalues) == 41016);
P386_LAYOUT_STATIC_ASSERT(vm_call_stack, offsetof(P386VMState, call_stack) == 41020);
P386_LAYOUT_STATIC_ASSERT(vm_call_depth, offsetof(P386VMState, call_depth) == 49212);
P386_LAYOUT_STATIC_ASSERT(vm_vararg_base, offsetof(P386VMState, vararg_base) == 49216);
P386_LAYOUT_STATIC_ASSERT(vm_vararg_count, offsetof(P386VMState, vararg_count) == 49220);
P386_LAYOUT_STATIC_ASSERT(vm_vararg_sp, offsetof(P386VMState, vararg_sp) == 49224);
P386_LAYOUT_STATIC_ASSERT(vm_vararg_stack, offsetof(P386VMState, vararg_stack) == 49228);
P386_LAYOUT_STATIC_ASSERT(proto_size, sizeof(P386ProtoEntry) == 24);
P386_LAYOUT_STATIC_ASSERT(proto_bytecode_off, offsetof(P386ProtoEntry, bytecode_off) == 0);
P386_LAYOUT_STATIC_ASSERT(proto_bytecode_len, offsetof(P386ProtoEntry, bytecode_len) == 4);
P386_LAYOUT_STATIC_ASSERT(proto_consts_off, offsetof(P386ProtoEntry, consts_off) == 8);
P386_LAYOUT_STATIC_ASSERT(proto_upvals_off, offsetof(P386ProtoEntry, upvals_off) == 12);
P386_LAYOUT_STATIC_ASSERT(proto_n_consts, offsetof(P386ProtoEntry, n_consts) == 22);
P386_LAYOUT_STATIC_ASSERT(proto_n_params, offsetof(P386ProtoEntry, n_params) == 17);
P386_LAYOUT_STATIC_ASSERT(proto_n_regs, offsetof(P386ProtoEntry, n_regs) == 18);
P386_LAYOUT_STATIC_ASSERT(proto_n_upvalues, offsetof(P386ProtoEntry, n_upvalues) == 19);
P386_LAYOUT_STATIC_ASSERT(proto_flags, offsetof(P386ProtoEntry, flags) == 20);
P386_LAYOUT_STATIC_ASSERT(string_entry_size, sizeof(P386StringEntry) == 8);
P386_LAYOUT_STATIC_ASSERT(string_entry_data_off, offsetof(P386StringEntry, data_off) == 0);
P386_LAYOUT_STATIC_ASSERT(string_entry_len, offsetof(P386StringEntry, len) == 4);
P386_LAYOUT_STATIC_ASSERT(tag_nil, P386_TAG_NIL == 0);
P386_LAYOUT_STATIC_ASSERT(tag_bool, P386_TAG_BOOL == 1);
P386_LAYOUT_STATIC_ASSERT(tag_num, P386_TAG_NUM == 2);
P386_LAYOUT_STATIC_ASSERT(tag_str, P386_TAG_STR == 3);
P386_LAYOUT_STATIC_ASSERT(tag_tab, P386_TAG_TAB == 4);
P386_LAYOUT_STATIC_ASSERT(tag_func, P386_TAG_FUNC == 5);
P386_LAYOUT_STATIC_ASSERT(tag_cfunc, P386_TAG_CFUNC == 6);
P386_LAYOUT_STATIC_ASSERT(vm_halted, P386_VM_HALTED == 1);
P386_LAYOUT_STATIC_ASSERT(err_opcode, P386_VM_ERR_OPCODE == -2);
P386_LAYOUT_STATIC_ASSERT(err_type, P386_VM_ERR_TYPE == -3);
P386_LAYOUT_STATIC_ASSERT(err_div0, P386_VM_ERR_DIV0 == -4);
P386_LAYOUT_STATIC_ASSERT(err_bounds, P386_VM_ERR_BOUNDS == -5);
P386_LAYOUT_STATIC_ASSERT(err_unimpl, P386_VM_ERR_UNIMPL == -6);
P386_LAYOUT_STATIC_ASSERT(call_frame_post, offsetof(P386CallFrame, post) == 18);
P386_LAYOUT_STATIC_ASSERT(table_metatable, offsetof(P386Table, metatable) == 16);
P386_LAYOUT_STATIC_ASSERT(table_arr, offsetof(P386Table, arr) == 0);
P386_LAYOUT_STATIC_ASSERT(table_asize, offsetof(P386Table, asize) == 4);
P386_LAYOUT_STATIC_ASSERT(table_hash, offsetof(P386Table, hash) == 12);
P386_LAYOUT_STATIC_ASSERT(table_hcap, offsetof(P386Table, hcap) == 20);
P386_LAYOUT_STATIC_ASSERT(table_entry_size, sizeof(P386TableEntry) == 16);
P386_LAYOUT_STATIC_ASSERT(string_hash, offsetof(P386String, hash) == 4);
P386_LAYOUT_STATIC_ASSERT(vm_stack_start, offsetof(P386VMState, stack_start) == 51276);
P386_LAYOUT_STATIC_ASSERT(vm_frames, offsetof(P386VMState, frames) == 51280);
P386_LAYOUT_STATIC_ASSERT(vm_frames_max, offsetof(P386VMState, frames_max) == 51284);
P386_LAYOUT_STATIC_ASSERT(vm_varargs, offsetof(P386VMState, varargs) == 51288);
P386_LAYOUT_STATIC_ASSERT(vm_varargs_max, offsetof(P386VMState, varargs_max) == 51292);
P386_LAYOUT_STATIC_ASSERT(vm_ret_base, offsetof(P386VMState, ret_base) == 51296);
P386_LAYOUT_STATIC_ASSERT(vm_tail_reg, offsetof(P386VMState, tail_reg) == 51300);
P386_LAYOUT_STATIC_ASSERT(vm_kstr, offsetof(P386VMState, kstr) == 51304);
P386_LAYOUT_STATIC_ASSERT(vm_switch, P386_VM_SWITCH == -8);

#endif /* __386__ */

#undef P386_LAYOUT_STATIC_ASSERT

#endif /* P386_LAYOUT_H */
