#!/usr/bin/env python3
import argparse
from pathlib import Path
from p386_layout import ASM_CONSTANTS, C_ASSERTS

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "include" / "p386_layout.h"
INC = ROOT / "src" / "p386_layout.inc"

HEADER_PREAMBLE = """/* Generated by tools/gen_p386_layout.py; do not edit by hand.\n * Included after p386 VM/bytecode structs are declared.\n */\n#ifndef P386_LAYOUT_H\n#define P386_LAYOUT_H\n\n#include <stddef.h>\n\n#define P386_LAYOUT_STATIC_ASSERT(name, cond) \\\n    typedef char p386_layout_static_assert_##name[(cond) ? 1 : -1]\n\n/* These offsets are for the 32-bit DOS ABI used by the NASM dispatcher. */\n#ifdef __386__\nP386_LAYOUT_STATIC_ASSERT(pointer_size_32bit, sizeof(void *) == 4);\n\n"""
HEADER_POSTAMBLE = """\n#endif /* __386__ */\n\n#undef P386_LAYOUT_STATIC_ASSERT\n\n#endif /* P386_LAYOUT_H */\n"""


def render_header():
    lines = [HEADER_PREAMBLE]
    for name, expr in C_ASSERTS:
        lines.append(f"P386_LAYOUT_STATIC_ASSERT({name}, {expr});\n")
    lines.append(HEADER_POSTAMBLE)
    return "".join(lines)


def render_inc():
    width = max(len(name) for name, _ in ASM_CONSTANTS)
    lines = ["; Generated by tools/gen_p386_layout.py; do not edit by hand.\n"]
    for name, value in ASM_CONSTANTS:
        lines.append(f"%define {name:<{width}} {value}\n")
    return "".join(lines)


def write_if_changed(path, data):
    if path.exists() and path.read_text() == data:
        return False
    path.write_text(data)
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = ap.parse_args()
    outputs = [(HEADER, render_header()), (INC, render_inc())]
    if args.check:
        stale = [str(p.relative_to(ROOT)) for p, data in outputs if not p.exists() or p.read_text() != data]
        if stale:
            raise SystemExit("stale generated layout files: " + ", ".join(stale) + " (run tools/gen_p386_layout.py)")
        return
    for p, data in outputs:
        write_if_changed(p, data)

if __name__ == "__main__":
    main()
