#!/usr/bin/env python3
"""Generate a fixed-point (16.16) sine lookup table for the PICO-8 VM.

PICO-8 trig is turns-based: a full circle is 1.0, not 2*pi. We emit one full
turn sampled at TRIG_N points so the runtime can index without an FPU (the 386
target may have no 387). sin/cos are derived from this single table at runtime.

Table entry i = round( sin(2*pi*i / TRIG_N) * 65536 ), i in [0, TRIG_N).
"""
import math

TRIG_N = 1024  # power of two: index = (frac_turn_fp >> 6)

def main():
    vals = []
    for i in range(TRIG_N):
        s = math.sin(2.0 * math.pi * i / TRIG_N)
        fp = int(round(s * 65536.0))
        # clamp to int32 range (1.0 -> 65536 fits)
        vals.append(fp)
    lines = []
    lines.append("/* Generated by tools/gen_trig_table.py - DO NOT EDIT. */")
    lines.append("/* sin(2*pi*i/%d) in 16.16 fixed point, one full turn. */" % TRIG_N)
    lines.append("#define P386_TRIG_N %d" % TRIG_N)
    lines.append("#define P386_TRIG_SHIFT %d" % (16 - TRIG_N.bit_length() + 1))
    lines.append("static const int32_t p386_sin_table[P386_TRIG_N] = {")
    row = []
    for idx, v in enumerate(vals):
        row.append("%d" % v)
        if len(row) == 8:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    out = "\n".join(lines) + "\n"
    with open("src/p386_trig.inc", "w") as f:
        f.write(out)
    print("wrote src/p386_trig.inc (%d entries, shift=%d)" %
          (TRIG_N, 16 - TRIG_N.bit_length() + 1))

if __name__ == "__main__":
    main()
