#!/usr/bin/env python3
"""Source-of-truth constants for C/ASM pico386 VM layout checks.

The values here describe the 32-bit DOS ABI consumed by src/p386_dispatch.asm.
Generated outputs:
  - include/p386_layout.h: C static assertions against real struct layout
  - src/p386_layout.inc: NASM %define constants used by the dispatcher
"""

ASM_CONSTANTS = [
    ("VM_STATUS", 0),
    ("VM_ERROR_MSG", 4),
    ("VM_LAST_OPCODE", 8),
    ("VM_PROGRAM", 12),
    ("LP_BUF", 0),
    ("LP_BUF_SIZE", 4),
    ("LP_PROTOS", 8),
    ("LP_STRING_ENTRIES", 12),
    ("LP_BYTECODE_SECTION", 16),
    ("VM_VALUE_STACK", 32),
    ("VM_BASE", 32800),
    ("VM_TOP", 32804),
    ("VM_VALUE_STACK_END", 32808),
    ("VM_GLOBALS", 32812),
    ("VM_CURRENT_PROTO", 34860),
    ("VM_IP", 34864),
    ("VM_CURRENT_CLOSURE", 34868),
    ("VM_OPEN_UPVALUES", 34872),
    ("VM_CALL_STACK", 34876),
    ("VM_CALL_DEPTH", 39996),
    ("FRAME_RETURN_IP", 0),
    ("FRAME_RETURN_BASE", 4),
    ("FRAME_RETURN_PROTO", 8),
    ("FRAME_RETURN_CLOSURE", 12),
    ("FRAME_RETURN_REG", 16),
    ("FRAME_WANT_RETS", 17),
    ("FRAME_SIZE", 20),
    ("CALL_STACK_DEPTH", 256),
    ("PE_BYTECODE_OFF", 0),
    ("PE_BYTECODE_LEN", 4),
    ("PE_CONSTS_OFF", 8),
    ("PE_UPVALS_OFF", 12),
    ("PE_N_CONSTS", 16),
    ("PE_N_PARAMS", 17),
    ("PE_N_REGS", 18),
    ("PE_N_UPVALUES", 19),
    ("PE_FLAGS", 20),
    ("SE_DATA_OFF", 0),
    ("SE_LEN", 4),
    ("VALUE_VALUE", 0),
    ("VALUE_TAG", 4),
    ("TAG_NIL", 0),
    ("TAG_BOOL", 1),
    ("TAG_NUM", 2),
    ("TAG_STR", 3),
    ("TAG_TAB", 4),
    ("TAG_FUNC", 5),
    ("TAG_CFUNC", 6),
    ("VM_HALTED", 1),
    ("ERR_OPCODE", -2),
    ("ERR_TYPE", -3),
    ("ERR_DIV0", -4),
    ("ERR_BOUNDS", -5),
    ("ERR_UNIMPL", -6),
]

C_ASSERTS = [
    ("p386_value_size", "sizeof(P386Value) == 8"),
    ("p386_value_value", "offsetof(P386Value, value) == 0"),
    ("p386_value_tag", "offsetof(P386Value, tag) == 4"),
    ("loaded_program_size", "sizeof(P386LoadedProgram) == 20"),
    ("loaded_program_buf", "offsetof(P386LoadedProgram, buf) == 0"),
    ("loaded_program_buf_size", "offsetof(P386LoadedProgram, buf_size) == 4"),
    ("loaded_program_protos", "offsetof(P386LoadedProgram, protos) == 8"),
    ("loaded_program_string_entries", "offsetof(P386LoadedProgram, string_entries) == 12"),
    ("loaded_program_bytecode_section", "offsetof(P386LoadedProgram, bytecode_section) == 16"),
    ("vm_status", "offsetof(P386VMState, status) == 0"),
    ("vm_error_msg", "offsetof(P386VMState, error_msg) == 4"),
    ("vm_last_opcode", "offsetof(P386VMState, last_opcode) == 8"),
    ("vm_program", "offsetof(P386VMState, program) == 12"),
    ("vm_value_stack", "offsetof(P386VMState, value_stack) == 32"),
    ("vm_base", "offsetof(P386VMState, base) == 32800"),
    ("vm_top", "offsetof(P386VMState, top) == 32804"),
    ("vm_value_stack_end", "offsetof(P386VMState, value_stack_end) == 32808"),
    ("vm_globals", "offsetof(P386VMState, globals) == 32812"),
    ("vm_current_proto", "offsetof(P386VMState, current_proto) == 34860"),
    ("vm_ip", "offsetof(P386VMState, ip) == 34864"),
    ("call_frame_size", "sizeof(P386CallFrame) == 20"),
    ("call_frame_return_ip", "offsetof(P386CallFrame, return_ip) == 0"),
    ("call_frame_return_base", "offsetof(P386CallFrame, return_base) == 4"),
    ("call_frame_return_proto", "offsetof(P386CallFrame, return_proto) == 8"),
    ("call_frame_return_closure", "offsetof(P386CallFrame, return_closure) == 12"),
    ("call_frame_return_reg", "offsetof(P386CallFrame, return_reg) == 16"),
    ("call_frame_want_rets", "offsetof(P386CallFrame, want_rets) == 17"),
    ("vm_current_closure", "offsetof(P386VMState, current_closure) == 34868"),
    ("vm_open_upvalues", "offsetof(P386VMState, open_upvalues) == 34872"),
    ("vm_call_stack", "offsetof(P386VMState, call_stack) == 34876"),
    ("vm_call_depth", "offsetof(P386VMState, call_depth) == 39996"),
    ("proto_size", "sizeof(P386ProtoEntry) == 24"),
    ("proto_bytecode_off", "offsetof(P386ProtoEntry, bytecode_off) == 0"),
    ("proto_bytecode_len", "offsetof(P386ProtoEntry, bytecode_len) == 4"),
    ("proto_consts_off", "offsetof(P386ProtoEntry, consts_off) == 8"),
    ("proto_upvals_off", "offsetof(P386ProtoEntry, upvals_off) == 12"),
    ("proto_n_consts", "offsetof(P386ProtoEntry, n_consts) == 16"),
    ("proto_n_params", "offsetof(P386ProtoEntry, n_params) == 17"),
    ("proto_n_regs", "offsetof(P386ProtoEntry, n_regs) == 18"),
    ("proto_n_upvalues", "offsetof(P386ProtoEntry, n_upvalues) == 19"),
    ("proto_flags", "offsetof(P386ProtoEntry, flags) == 20"),
    ("string_entry_size", "sizeof(P386StringEntry) == 8"),
    ("string_entry_data_off", "offsetof(P386StringEntry, data_off) == 0"),
    ("string_entry_len", "offsetof(P386StringEntry, len) == 4"),
    ("tag_nil", "P386_TAG_NIL == 0"),
    ("tag_bool", "P386_TAG_BOOL == 1"),
    ("tag_num", "P386_TAG_NUM == 2"),
    ("tag_str", "P386_TAG_STR == 3"),
    ("tag_tab", "P386_TAG_TAB == 4"),
    ("tag_func", "P386_TAG_FUNC == 5"),
    ("tag_cfunc", "P386_TAG_CFUNC == 6"),
    ("vm_halted", "P386_VM_HALTED == 1"),
    ("err_opcode", "P386_VM_ERR_OPCODE == -2"),
    ("err_type", "P386_VM_ERR_TYPE == -3"),
    ("err_div0", "P386_VM_ERR_DIV0 == -4"),
    ("err_bounds", "P386_VM_ERR_BOUNDS == -5"),
    ("err_unimpl", "P386_VM_ERR_UNIMPL == -6"),
]
